sudo: required
dist: trusty
language: python
python:
  - "2.7"

#before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get -qq update
  - sudo apt-get -y install ansible
  - sudo mkdir -p /srv

install:
  - pip install -r requirements.txt

script:
  #- sudo test/test.sh $(which testinfra)
  - sudo test/test.sh 
