sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install curl
  - curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
  - sudo bash bootstrap_salt.sh -d
  - git clone https://github.com/wicksy/laptop-build.git
  - sudo mkdir -p /srv
  - sudo ln -sf laptop-build/salt/roots /srv/salt
  - sudo ln -sf laptop-build/salt/pillar /srv/pillar
  - ls -l
  - sudo find /srv -follow -ls

script:
 - test/test.sh
