sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install curl
  - curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
  - sudo bash bootstrap_salt.sh -d

script:
 - test/test.sh
